### PR TITLE
Add JMX configuration options

### PR DESCRIPTION
**Pull request by davidgiesberg**
Should be pretty cut and dry - just add the ability to configure JMX.

### CODE REVIEW

**Comment by mathyourlife** [comment]
:+1: Thanks David

**Comment by mathyourlife** [comment]
Bumped to 1.3.0 since technically a new feature, and uploaded to https://supermarket.chef.io/cookbooks/apache_kafka

**Comment by davidgiesberg** [comment]
Hmm, I just discovered a potential snag: we're sourcing `/etc/default/kafka` in the Upstart config _and_ in `kafka-run-class.sh`. That leads to errors like this:

```
$ ./kafka-run-class.sh kafka.tools.ConsumerOffsetChecker
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 7199; nested exception is:
    java.net.BindException: Address already in use
```

**Comment by mathyourlife** [comment]
There's a PR #12 that will use the packaged bash scripts which won't source
/etc/default/kafka

**Comment by davidgiesberg** [comment]
Ah, that's a good approach. However, I think I'm going to take a middle-ground approach which will work for my particular use case. In a wrapper cookbook, I'll put a shim in that will source `/etc/default/kafka`, make whatever resets/overrides I need to make, and then source the packaged scripts.

```
#!/bin/bash
source /etc/default/kafka

JMX_PORT=""
LOG_DIR="/var/log/kafka"

source /opt/kafka/kafka_2.11-0.8.2.1/bin/kafka-run-class.sh
```

**Comment by mathyourlife** [comment]
It's looking like using the original untar'd files won't work in the current setup.  I have a patch PR for fixing the double source #15 if you'd care to review @davidgiesberg

**Comment by justizin** [comment]
Ah, seeing the justification for #15 now, I like the shim idea.

**Pull request merged**
